<?php
/** @var \Team\Entity\TournamentStatus $tournamentStatus */
?>
<?php if ($tournamentStatus->getStatusId() === \Team\Entity\TournamentStatus::STATUS_CREATE_TEAM): ?>
    <a href="<?= $this->url('team', ['action' => 'teamCreate']) ?>"
       type="button" class="btn btn-primary">Add team</a>
<?php endif; ?>
<?php if (in_array($tournamentStatus->getStatusId(),
    [\Team\Entity\TournamentStatus::STATUS_SPLIT_TEAM, \Team\Entity\TournamentStatus::STATUS_CREATE_TEAM])): ?>
    <a href="<?= $this->url('team', ['action' => 'splitTeams']) ?>"
       type="button" class="btn btn-primary">Divide teams into divisions</a>
<?php endif; ?>
<?php if (in_array($tournamentStatus->getStatusId(),
    [\Team\Entity\TournamentStatus::STATUS_SPLIT_TEAM, \Team\Entity\TournamentStatus::STATUS_SPLIT_MATCH])): ?>
    <a href="<?= $this->url('team', ['action' => 'teamTossQualification']) ?>"
       type="button" class="btn btn-primary">The draw (who will play with anyone)</a>
<?php endif; ?>