<?php
/** @var \Team\Entity\TeamMatch[] $matches */
/** @var \Team\Classes\PlayoffFinishedMatch[] $prevMatch */
/** @var \Team\Entity\TournamentStatus $tournamentStatus */
/** @var string $currentTitle */
/** @var \Team\Entity\Team $winTeam */
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Playoff</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php if($winTeam): ?>
<div class="row">
    <div class="panel panel-success">
        <div class="panel-heading">
            Winner
        </div>
        <div class="panel-body">
            <p><?=$winTeam->getTitle()?></p>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="panel-body">
    <?php if (count($matches) > 0): ?>
        <?= $this->partial('partial/button/playoff.phtml', ['tournamentStatus' => $tournamentStatus]) ?>
        <?= $this->flashMessenger()->render('error') ?>
        <?php if ($tournamentStatus->getStatusId() === \Team\Entity\TournamentStatus::STATUS_SPLIT_MATCH_PLAYOFF): ?>
            <?= $this->partial('partial/stage5.phtml', ['matches' => $matches, 'currentTitle' => $currentTitle]) ?>
        <?php else: ?>
            <?= $this->partial('partial/stage6.phtml', ['matches' => $matches, 'prevMatch' => $prevMatch, 'currentTitle' => $currentTitle]) ?>
        <?php endif; ?>
    <?php else: ?>
        Распределения еще не было
    <?php endif; ?>
</div>