<?php
/** @var \Team\Entity\TeamMatch[] $matches */
/** @var \Team\Entity\TournamentStatus $tournamentStatus */
/** @var string $title */
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Qualifying</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="panel-body">
    <?php if (count($matches) > 0): ?>
        <?= $this->partial('partial/button/qualifying.phtml', ['tournamentStatus' => $tournamentStatus]) ?>

        <?= $this->flashMessenger()->render('error') ?>
        <?php if ($tournamentStatus->getStatusId() === \Team\Entity\TournamentStatus::STATUS_SPLIT_MATCH): ?>
            <?= $this->partial('partial/stage3.phtml', ['matches' => $matches]) ?>
        <?php else: ?>
            <?= $this->partial('partial/stage4.phtml', ['matches' => $matches]) ?>
        <?php endif; ?>
    <?php else: ?>
        Распределения еще не было
    <?php endif; ?>
</div>