<?php
/**
 * @var \Team\Form\TeamForm $form
 */
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Team create</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?= $this->form()->openTag($form) ?>
                        <?php
                            // Выводим текущие ошибки
                            echo $this->flashMessenger()->renderCurrent('error');
                            $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
                        ?>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('title')); ?>
                            <?= $this->formElement($form->get('title')); ?>
                            <?= $this->formElementErrors($form->get('title')); ?>
                        </div>
                        <?= $this->formHidden($form->get('csrf')) ?>
                        <?= $this->formRow($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
