<?php
/** @var \Team\Entity\Team[] $teams */
/** @var \Team\Entity\TournamentStatus $tournamentStatus */
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Teams</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="panel-body">
    <?= $this->partial('partial/button/teamList.phtml', ['tournamentStatus' => $tournamentStatus]) ?>
    <?= $this->flashMessenger()->render('error') ?>

    <?php if ($tournamentStatus->getStatusId() === \Team\Entity\TournamentStatus::STATUS_CREATE_TEAM): ?>
        <?= $this->partial('partial/stage1.phtml', ['teams' => $teams]) ?>
    <?php else: ?>
        <?= $this->partial('partial/stage2.phtml', ['teams' => $teams]) ?>
    <?php endif; ?>
</div>