<?php
/** @var \Team\Entity\TeamMatch[] $matches */
?>
<div class="row">
    <div class="col-lg-6">
        <?= $this->partial('partial/match.phtml', ['matches' => $matches, 'groupName' => \Team\Entity\TeamSplit::GROUP1]) ?>
    </div>
    <div class="col-lg-6">
        <?= $this->partial('partial/match.phtml', ['matches' => $matches, 'groupName' => \Team\Entity\TeamSplit::GROUP2]) ?>
    </div>
</div>